# Recommended configuration for Spring Boot application

spring:
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/PRACTICE_SCHEDULE_WEBSITE_DB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: create-drop # 'none' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080